alias: "Pixel Matrix: 64x16 Demo Loop"
description: >-
  Demonstracja dla szerokiego ekranu 64x16: Zegar, Pogoda, Grafika i
  Powiadomienia.
triggers:
  - seconds: /10
    trigger: time_pattern
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 0 }}"
        sequence:
          - target:
              entity_id: light.display_efd943
            data:
              transition:
                type: slide_up
                duration: 0.8
                fps: 30
              background:
                - 0
                - 0
                - 0
              elements:
                - type: icon
                  name: mdi:weather-partly-cloudy
                  x: 0
                  "y": 0
                  size: 16
                  color:
                    - 255
                    - 255
                    - 0
                - type: text
                  content: "{{ now().strftime('%H:%M') }}"
                  x: 18
                  "y": 0
                  font: 5x7
                  color:
                    - 0
                    - 255
                    - 255
                - type: text
                  content: 21°C
                  x: 18
                  "y": 8
                  font: 5x7
                  color:
                    - 255
                    - 100
                    - 100
            action: unexpected_matrix_pixels.draw_matrix
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 1 }}"
        sequence:
          - target:
              entity_id: light.display_efd943
            data:
              transition:
                type: dissolve
                duration: 1
              background:
                - 10
                - 10
                - 20
              elements:
                - type: pixels
                  pixels:
                    - - 5
                      - 15
                      - 0
                      - 255
                      - 0
                    - - 5
                      - 14
                      - 0
                      - 255
                      - 0
                    - - 5
                      - 13
                      - 255
                      - 255
                      - 0
                    - - 15
                      - 15
                      - 0
                      - 255
                      - 0
                    - - 15
                      - 14
                      - 0
                      - 255
                      - 0
                    - - 15
                      - 13
                      - 0
                      - 255
                      - 0
                    - - 15
                      - 12
                      - 255
                      - 255
                      - 0
                    - - 15
                      - 11
                      - 255
                      - 0
                      - 0
                    - - 25
                      - 15
                      - 0
                      - 255
                      - 0
                    - - 25
                      - 14
                      - 255
                      - 255
                      - 0
                    - - 35
                      - 15
                      - 0
                      - 255
                      - 0
                    - - 35
                      - 14
                      - 0
                      - 255
                      - 0
                    - - 35
                      - 13
                      - 0
                      - 255
                      - 0
                    - - 45
                      - 15
                      - 0
                      - 255
                      - 0
                    - - 45
                      - 14
                      - 0
                      - 255
                      - 0
                    - - 45
                      - 13
                      - 0
                      - 255
                      - 0
                    - - 45
                      - 12
                      - 255
                      - 255
                      - 0
                - type: text
                  content: MUSIC
                  x: 35
                  "y": 2
                  font: 3x5
                  color:
                    - 200
                    - 200
                    - 255
            action: unexpected_matrix_pixels.draw_matrix
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 2 }}"
        sequence:
          - target:
              entity_id: light.display_efd943
            data:
              transition:
                type: slide_left
                duration: 0.8
              background:
                - 255
                - 255
                - 255
              elements:
                - type: image
                  url: https://brands.home-assistant.io/_/homeassistant/icon.png
                  x: 2
                  "y": 0
                  width: 16
                  height: 16
                - type: text
                  content: HOME ASSISTANT
                  x: 20
                  "y": 5
                  font: 3x5
                  color:
                    - 0
                    - 0
                    - 0
            action: unexpected_matrix_pixels.draw_matrix
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 3 }}"
        sequence:
          - target:
              entity_id: light.display_efd943
            data:
              transition:
                type: slide_right
                duration: 0.8
              background:
                - 0
                - 50
                - 0
              elements:
                - type: icon
                  name: mdi:check-circle
                  x: 2
                  "y": 0
                  size: 16
                  color:
                    - 0
                    - 255
                    - 0
                - type: text
                  content: SYSTEM OK
                  x: 20
                  "y": 4
                  font: 5x7
                  color:
                    - 255
                    - 255
                    - 255
            action: unexpected_matrix_pixels.draw_matrix
mode: restart
