alias: "Pixel Matrix: 32x32 Demo Loop"
description: "Demo"
triggers:
  - seconds: /10
    trigger: time_pattern
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 0 }}"
        sequence:
          - target:
              entity_id: light.display_4dfcd4
            data:
              transition:
                type: slide_up
                duration: 0.8
                fps: 20
              background:
                - 0
                - 0
                - 50
              elements:
                - type: text
                  content: "{{ now().strftime('%H:%M') }}"
                  x: 6
                  "y": 2
                  font: awtrix
                  color:
                    - 0
                    - 255
                    - 255
                - type: icon
                  name: mdi:weather-sunny
                  x: 8
                  "y": 12
                  size: 16
                  color:
                    - 255
                    - 200
                    - 0
            action: unexpected_matrix_pixels.draw_matrix
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 1 }}"
        sequence:
          - target:
              entity_id: light.display_4dfcd4
            data:
              transition:
                type: dissolve
                duration: 1.5
                fps: 20
              background:
                - 0
                - 0
                - 0
              elements:
                - type: pixels
                  pixels:
                    - - 14
                      - 10
                      - 255
                      - 0
                      - 0
                    - - 17
                      - 10
                      - 255
                      - 0
                      - 0
                    - - 13
                      - 11
                      - 255
                      - 0
                      - 0
                    - - 15
                      - 11
                      - 255
                      - 0
                      - 0
                    - - 16
                      - 11
                      - 255
                      - 0
                      - 0
                    - - 18
                      - 11
                      - 255
                      - 0
                      - 0
                    - - 13
                      - 12
                      - 255
                      - 0
                      - 0
                    - - 18
                      - 12
                      - 255
                      - 0
                      - 0
                    - - 14
                      - 13
                      - 255
                      - 0
                      - 0
                    - - 17
                      - 13
                      - 255
                      - 0
                      - 0
                    - - 15
                      - 14
                      - 255
                      - 0
                      - 0
                    - - 16
                      - 14
                      - 255
                      - 0
                      - 0
                    - - 15
                      - 15
                      - 255
                      - 0
                      - 0
                - type: text
                  content: LOVE
                  x: 8
                  "y": 20
                  font: 3x5
                  color:
                    - 255
                    - 100
                    - 100
            action: unexpected_matrix_pixels.draw_matrix
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 2 }}"
        sequence:
          - target:
              entity_id: light.display_4dfcd4
            data:
              transition:
                type: slide_left
                duration: 0.6
                fps: 20
              background:
                - 0
                - 0
                - 0
              elements:
                - type: image
                  url: https://brands.home-assistant.io/_/homeassistant/icon.png
                  x: 0
                  "y": 0
                  width: 32
                  height: 32
            action: unexpected_matrix_pixels.draw_matrix
      - conditions:
          - condition: template
            value_template: "{{ (now().second // 10) % 4 == 3 }}"
        sequence:
          - target:
              entity_id: light.display_4dfcd4
            data:
              transition:
                type: slide_right
                duration: 0.8
              background:
                - 0
                - 30
                - 0
              elements:
                - type: text
                  content: DOM
                  x: 10
                  "y": 5
                  font: awtrix
                  color:
                    - 255
                    - 255
                    - 255
                - type: icon
                  name: mdi:home-assistant
                  x: 8
                  "y": 14
                  size: 16
                  color:
                    - 0
                    - 200
                    - 255
            action: unexpected_matrix_pixels.draw_matrix
mode: restart
